### PR TITLE
Minor cleanup and nitpicks

### PR DESCRIPTION
**Pull request by davidalayachew**
This pull request just cleans up some typos and nitpicks here and there.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/babylon-docs.git pull/2/head:pull/2` \
`$ git checkout pull/2`

Update a local copy of the PR: \
`$ git checkout pull/2` \
`$ git pull https://git.openjdk.org/babylon-docs.git pull/2/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2`

View PR using the GUI difftool: \
`$ git pr show -t 2`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/babylon-docs/pull/2.diff">https://git.openjdk.org/babylon-docs/pull/2.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/babylon-docs/pull/2#issuecomment-1925659925)

### CODE REVIEW

**Comment by davidalayachew** [comment]
There's probably more things to fix in this, but my eyes are still spinning.

**Comment by davidalayachew** [comment]
> /sponsor

Lol, I love that the solution was just to hit it again.

**Comment by PaulSandoz** [comment]
Thank you for the edits (the intention was to always copy code from the test classes, but somehow they got out of sync as if often the case when taking short cuts)

**Comment by davidalayachew** [comment]
> Thank you for the edits (the intention was to always copy code from the test classes, but somehow they got out of sync as if often the case when taking short cuts)

Happy to help! The project is something that I am extremely excited for, and I've been reading the one doc you posted so much that these nits stood out to me. I'll post more pull requests as I find more stuff to clean up.

**Pull request closed without merging**
